services:
  postgres:
    image: postgres
    container_name: Talos-postgres
    environment:
      POSTGRES_DB: Talos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "3101:5432"
    volumes:
      - Talos_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  Talos_postgres_data:
